#!/usr/bin/env python3
"""Generate canonical local API, TypeScript, and Rust route artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
CORE_SRC = ROOT / "services" / "core" / "src"
sys.path.insert(0, str(CORE_SRC))

from ariadne_core.api.app import create_contract_app  # noqa: E402

OPENAPI_PATH = ROOT / "packages" / "contracts" / "openapi" / "ariadne-v1.json"
TYPESCRIPT_PATH = ROOT / "packages" / "contracts" / "src" / "generated" / "api.ts"
RUST_PATH = ROOT / "packages" / "contracts" / "src" / "generated" / "route_allowlist.rs"


def _canonical(value: object) -> bytes:
    return json.dumps(
        value, ensure_ascii=False, separators=(",", ":"), sort_keys=True
    ).encode()


def _resolve_refs(
    value: Any, document: dict[str, Any], seen: frozenset[str] = frozenset()
) -> Any:
    if isinstance(value, list):
        return [_resolve_refs(item, document, seen) for item in value]
    if not isinstance(value, dict):
        return value
    reference = value.get("$ref")
    if isinstance(reference, str):
        if not reference.startswith("#/components/schemas/") or reference in seen:
            return value
        name = reference.rsplit("/", 1)[-1]
        target = document["components"]["schemas"][name]
        return _resolve_refs(target, document, seen | {reference})
    return {key: _resolve_refs(item, document, seen) for key, item in value.items()}


def _schema_hash(schema: dict[str, Any], document: dict[str, Any]) -> str:
    return hashlib.sha256(_canonical(_resolve_refs(schema, document))).hexdigest()


def _routes(document: dict[str, Any]) -> list[dict[str, Any]]:
    routes: list[dict[str, Any]] = []
    for path, path_item in sorted(document["paths"].items()):
        for method, operation in sorted(path_item.items()):
            if method.upper() not in {"GET", "POST", "PUT", "PATCH", "DELETE"}:
                continue
            capability = operation["x-ariadne-capability"]
            request_schema = (
                operation.get("requestBody", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema", {})
            )
            response_schema = operation["responses"]["200"]["content"][
                "application/json"
            ]["schema"]
            routes.append(
                {
                    **capability,
                    "method": method.upper(),
                    "path": path,
                    "requestSchemaSha256": _schema_hash(request_schema, document),
                    "responseSchemaSha256": _schema_hash(response_schema, document),
                }
            )
    return routes


def _ts_property_name(value: str) -> str:
    return (
        value if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", value) else json.dumps(value)
    )


def _ts_type(schema: dict[str, Any]) -> str:
    reference = schema.get("$ref")
    if isinstance(reference, str):
        return reference.rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    enum = schema.get("enum")
    if isinstance(enum, list):
        return " | ".join(json.dumps(item) for item in enum)
    variants = schema.get("anyOf") or schema.get("oneOf")
    if isinstance(variants, list):
        return " | ".join(_ts_type(item) for item in variants)
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            "null" if item == "null" else _ts_type({"type": item})
            for item in schema_type
        )
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"ReadonlyArray<{_ts_type(schema.get('items', {}))}>"
    if schema_type == "object" or "properties" in schema:
        required = set(schema.get("required", []))
        properties = schema.get("properties", {})
        fields = [
            "readonly "
            + _ts_property_name(name)
            + ("?" if name not in required else "")
            + ": "
            + _ts_type(value)
            + ";"
            for name, value in properties.items()
        ]
        return "{ " + " ".join(fields) + " }"
    return "unknown"


def _typescript(document: dict[str, Any], routes: list[dict[str, Any]]) -> str:
    lines = [
        "// Generated by packages/contracts/generate.py. Do not edit.",
        "",
    ]
    for name, schema in sorted(document["components"]["schemas"].items()):
        if schema.get("type") == "object" and "properties" in schema:
            required = set(schema.get("required", []))
            lines.append(f"export interface {name} {{")
            for property_name, value in schema["properties"].items():
                optional = "?" if property_name not in required else ""
                lines.append(
                    f"  readonly {_ts_property_name(property_name)}{optional}: {_ts_type(value)}"
                )
            lines.append("}")
        else:
            lines.append(f"export type {name} = {_ts_type(schema)}")
        lines.append("")

    lines.extend(
        [
            "export interface RouteCapability {",
            "  readonly routeId: string",
            "  readonly method: 'GET' | 'POST'",
            "  readonly path: string",
            "  readonly requestSchemaSha256: string",
            "  readonly responseSchemaSha256: string",
            "  readonly maxRequestBytes: number",
            "  readonly maxResponseBytes: number",
            "  readonly requiredLockState: 'ANY' | 'NO_VAULT' | 'LOCKED' | 'UNLOCKED'",
            "  readonly scopeClass: 'NONE' | 'VAULT' | 'PROFILE'",
            "  readonly revealClass: 'NONE'",
            "  readonly authorizationClass: 'LAUNCH_SESSION' | 'SHELL_INTERNAL' | 'USER_GESTURE' | 'USER_GESTURE_KEYCHAIN' | 'USER_GESTURE_FILE_PICKER'",
            "}",
            "",
            "export const ROUTE_CAPABILITIES = "
            + json.dumps(routes, indent=2, sort_keys=True)
            + " as const satisfies ReadonlyArray<RouteCapability>",
            "",
        ]
    )
    return "\n".join(lines)


def _rust(routes: list[dict[str, Any]]) -> str:
    lines = [
        "// Generated by packages/contracts/generate.py. Do not edit.",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub struct RouteCapability {",
        "    pub route_id: &'static str,",
        "    pub method: &'static str,",
        "    pub path: &'static str,",
        "    pub request_schema_sha256: &'static str,",
        "    pub response_schema_sha256: &'static str,",
        "    pub max_request_bytes: usize,",
        "    pub max_response_bytes: usize,",
        "    pub required_lock_state: &'static str,",
        "    pub scope_class: &'static str,",
        "    pub reveal_class: &'static str,",
        "    pub authorization_class: &'static str,",
        "}",
        "",
        "pub const ROUTE_CAPABILITIES: &[RouteCapability] = &[",
    ]
    for route in routes:
        lines.extend(
            [
                "    RouteCapability {",
                f"        route_id: {json.dumps(route['routeId'])},",
                f"        method: {json.dumps(route['method'])},",
                f"        path: {json.dumps(route['path'])},",
                f"        request_schema_sha256: {json.dumps(route['requestSchemaSha256'])},",
                f"        response_schema_sha256: {json.dumps(route['responseSchemaSha256'])},",
                f"        max_request_bytes: {route['maxRequestBytes']},",
                f"        max_response_bytes: {route['maxResponseBytes']},",
                f"        required_lock_state: {json.dumps(route['requiredLockState'])},",
                f"        scope_class: {json.dumps(route['scopeClass'])},",
                f"        reveal_class: {json.dumps(route['revealClass'])},",
                f"        authorization_class: {json.dumps(route['authorizationClass'])},",
                "    },",
            ]
        )
    lines.extend(["];"])
    return "\n".join(lines) + "\n"


def _artifacts() -> dict[Path, bytes]:
    document = create_contract_app().openapi()
    routes = _routes(document)
    return {
        OPENAPI_PATH: _canonical(document) + b"\n",
        TYPESCRIPT_PATH: _typescript(document, routes).encode(),
        RUST_PATH: _rust(routes).encode(),
    }


def generate(*, check: bool) -> int:
    stale: list[Path] = []
    for path, content in _artifacts().items():
        if check:
            if not path.is_file() or path.read_bytes() != content:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    if stale:
        for path in stale:
            print(
                f"stale generated contract: {path.relative_to(ROOT)}", file=sys.stderr
            )
        return 1
    return 0


def main(arguments: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parsed = parser.parse_args(arguments)
    return generate(check=parsed.check)


if __name__ == "__main__":
    raise SystemExit(main())
