[alembic]
script_location = %(here)s/migrations
prepend_sys_path = %(here)s/src
path_separator = os

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = null

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = null

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_null]
class = logging.NullHandler
args = ()
level = NOTSET

[formatter_generic]
format = %(levelname)s %(name)s %(message)s

