/**
 * Supplies a complete fictional audit graph for renderer and package tests;
 * reserved domains prevent the fixture from representing a real person.
 */
import type { AuditDetail } from '../../../../packages/contracts/src/generated/api'

const auditId = '11111111-1111-4111-8111-111111111111'
const profileId = '22222222-2222-4222-8222-222222222222'
const taskId = '33333333-3333-4333-8333-333333333333'
const resultId = '44444444-4444-4444-8444-444444444444'
const leadId = '55555555-5555-4555-8555-555555555555'
const proposalId = '66666666-6666-4666-8666-666666666666'
const receiptId = '77777777-7777-4777-8777-777777777777'
const analysisId = '88888888-8888-4888-8888-888888888888'

export const completedAuditDetail: AuditDetail = {
  profileId,
  audit: {
    auditId,
    name: 'Synthetic complete audit',
    mode: 'MAXIMUM_COVERAGE',
    state: 'COMPLETED',
    stage: 'COMPLETE',
    providerIds: ['DUCKDUCKGO_HTML'],
    useLocalAi: true,
    selectedModel: 'synthetic-local:1b',
    maxDepth: 2,
    requestBudget: 12,
    totalTasks: 1,
    terminalTasks: 1,
    resultCount: 1,
    leadCount: 1,
    proposalCount: 1,
    progressMicros: 1_000_000,
    stopReason: 'FRONTIER_EXHAUSTED',
    taskStates: [{ state: 'SUCCEEDED_RESULTS', count: 1 }],
    startedAtUs: 1_750_000_000_000_000,
    finishedAtUs: 1_750_000_001_000_000,
    createdAtUs: 1_750_000_000_000_000,
    updatedAtUs: 1_750_000_001_000_000,
    revision: 4,
  },
  tasks: [{
    taskId,
    leadId: null,
    parentTaskId: null,
    taskType: 'SEARCH_WEB',
    providerId: 'DUCKDUCKGO_HTML',
    maskedPayload: 's•••t',
    priority: 100,
    informationGainMicros: 800_000,
    depth: 0,
    state: 'SUCCEEDED_RESULTS',
    attemptCount: 1,
    retryLimit: 2,
    resultCount: 1,
    stopReason: null,
    revision: 2,
  }],
  results: [{
    resultId,
    taskId,
    providerId: 'DUCKDUCKGO_HTML',
    rank: 1,
    category: 'PUBLIC_PROFILE',
    url: 'https://profile.example.invalid/synthetic-result',
    title: 'Synthetic [profile] result',
    snippet: 'A synthetic result used only for package testing.',
    observedAtUs: 1_750_000_000_500_000,
    reviewState: 'REVIEWED',
  }],
  leads: [{
    leadId,
    parentLeadId: null,
    sourceId: null,
    leadType: 'URL',
    displayValue: 'profile.example.invalid',
    sourceUrl: 'https://profile.example.invalid/synthetic-result',
    providerId: 'DUCKDUCKGO_HTML',
    depth: 0,
    supportingSignals: ['EXACT_SOURCE'],
    contradictions: [],
    confidenceMicros: 900_000,
    ownershipState: 'POSSIBLE',
    temporalState: 'CURRENT',
    reviewState: 'REVIEWED',
    expansionState: 'COMPLETE',
  }],
  proposals: [{
    proposalId,
    leadId,
    entityType: 'USERNAME',
    displayValue: 's•••c',
    sourceUrl: 'https://profile.example.invalid/synthetic-result',
    sourceSpanStart: null,
    sourceSpanEnd: null,
    supportingSignals: ['EXACT_SOURCE'],
    contradictions: [],
    confidenceMicros: 750_000,
    temporalState: 'CURRENT',
    reviewState: 'CONFIRMED',
    recommendedActions: ['CONFIRM'],
    modelProvider: null,
    modelId: null,
    revision: 2,
  }],
  receipts: [{
    receiptId,
    taskId,
    toolName: 'SEARCH_WEB',
    authorizationState: 'APPROVED',
    executionState: 'SUCCEEDED_RESULTS',
    resultCode: 'RESULTS_RETURNED',
    resultCount: 1,
    modelProvider: null,
    modelId: null,
    startedAtUs: 1_750_000_000_100_000,
    finishedAtUs: 1_750_000_000_500_000,
  }],
  aiAnalysis: {
    analysisId,
    status: 'SUCCEEDED',
    resultCode: 'LOCAL_MODEL_SUCCEEDED',
    provider: 'OLLAMA',
    modelId: 'synthetic-local:1b',
    engineVersion: '1',
    title: 'Synthetic cited analysis',
    summary: 'One exact result is ready for review.',
    insights: [{
      kind: 'FACT',
      statement: 'A synthetic public result was returned.',
      rationale: 'The exact source URL was retained.',
      confidence: 'HIGH',
      evidenceRefs: ['result:synthetic-1'],
    }],
    citations: [{
      referenceId: 'result:synthetic-1',
      resultId,
      url: 'https://profile.example.invalid/synthetic-result',
      title: 'Synthetic profile result',
    }],
    limitations: ['Synthetic output requires human review.'],
    createdAtUs: 1_750_000_000_800_000,
  },
  hasMoreTasks: false,
  hasMoreResults: false,
  hasMoreLeads: false,
  hasMoreProposals: false,
  hasMoreReceipts: false,
}
