"""Bounded, local-only intake decoding and parsing primitives."""

from ariadne_core.intake.isolation import (
    IsolationError,
    IsolationErrorCode,
    IsolationLimits,
    IsolationOperation,
    parse_decoded_source_isolated,
    parse_file_isolated,
    parse_pasted_text_isolated,
)
from ariadne_core.intake.parsing import (
    DecodedSource,
    ParsedSource,
    ParserLimits,
    PreparseDecision,
    SafeParseError,
    SafeParseErrorCode,
    SegmentGate,
    SourceFormat,
    SourceSegment,
    SourceSegmentKind,
    decode_file,
    decode_pasted_text,
    decode_selected_bytes,
    parse_decoded_source,
    parse_file,
    parse_pasted_text,
)

__all__ = [
    "DecodedSource",
    "IsolationError",
    "IsolationErrorCode",
    "IsolationLimits",
    "IsolationOperation",
    "ParsedSource",
    "ParserLimits",
    "PreparseDecision",
    "SafeParseError",
    "SafeParseErrorCode",
    "SegmentGate",
    "SourceFormat",
    "SourceSegment",
    "SourceSegmentKind",
    "decode_file",
    "decode_pasted_text",
    "decode_selected_bytes",
    "parse_decoded_source",
    "parse_decoded_source_isolated",
    "parse_file",
    "parse_file_isolated",
    "parse_pasted_text",
    "parse_pasted_text_isolated",
]
